// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 5.4
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"slices",prev:"",next:"",duration:15*100,delay:10*100,width:1367,height:310,autoPlay:true,playPause:true,stopOnHover:false,loop:true,bullets:true,caption:false,captionEffect:"move",controls:true,onBeforeStep:0,images:0});